name: Docker Image CI

on:
     
#   push:
#     branches: 
#         - Clean_Architecture_With_Cubit
#   pull_request:
#     branches: 
#         - Clean_Architecture_With_Cubit

    workflow_dispatch: 
      inputs:
        release_name:
          default: 'v1.0.0'
          description: 'This is a release for Clean Architecture version 1.0.0. Using Cubit and Provider for State mangement.' 
          required: true

        release_tag:
          default: 'v1.0.0'
          description: 'Clean Architecture'
          required: true
          

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository 
      uses: actions/checkout@v2
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'

    - name: Install dependencies
      run: flutter pub get    

    - name: Build web app
      run: flutter build web --release

    - name: Update base href
      run: sed -i 's|<base href="/">|<base href="/flutter_projects/">|' build/web/index.html
    
    - name: Docker Build and Publish
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: shanu1690/clean-architecture-docker
          TAG: latest
      run: |
          docker build -t $IMAGE_NAME:$TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $IMAGE_NAME:$TAG

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web