name: Docker Image CI

on:
  push:
    branches: 
        - Clean_Architecture_With_Cubit
  pull_request:
    branches: 
        - Clean_Architecture_With_Cubit

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag clean-architecture:$(date +%s)